let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hVhbd+I4Ev4rOjztntM+7Sskj8JgSCYOtE13pmd2HhwjwLvGpmU7Pfz7rZJ8k0h68kCgvk+30lelkv78c2Kb8GdPPk38857ELK2zsoBflkmDyV+fBO5ZFliCUDfvpNnww1iBHMsyEaKOQRkvyeZSkfhSq5yVZ5ktx7BM5Ci4a0I3iLtGFC5UyDYtCSlm6lo2msOq0EdzujWuv5B2mfDjJaY9SikYNvGDarZss3XMtqxqDXM9xLI3svzRJDks4KIR7rDxQ1Hzos4JPRySjFca5R4pj3SlmaloqVvnaN1SzeqLKZ6SS55khYYtEIuTA6uvGvJVIHQbqXbPFL2V50vNyzxnXIfRwS+rz75PXrL6dCrzPRq6rx1N7GwQalP1HLOTkWJ1pYqWm+8aIvTls6ImYXEkcXoqyxw9iHrrObit2922/ezNDq5vt7W6fz2Ao31neV7+JFH2+irE/j0acE+2sLt/EnCokMI83LWf0uzaQnLgsPNI5cMa7k2zFQHjrKqJL2Xkh9ue4Ipd9WMDpDT6JmFKRXu6C7ZKv+tH4eI4iA1dtI+BDEvD8cj2YaNgUSiiYLR1/UwsWPq9mGpRviWYBEjEkn1WsKoiOw7ayooj4lG7dghyMXV/Hj0vMeziVQfMhK+ipDgy3K7NAEytDhDuCn+Px/i9KVa18TftpzQHX4QTAsOailYQj3zcDHCrdXKu2q1/aGehN2jGU85+kiCvMZSzi8oRa3G9GUFf3/YCyUgEcfj7yngqj2SbJ0Ulf3cEe9oRgoblGuiYHQhO1lu65rjrfj9UkteSYqnAH/tCw+fWCIdVqvC0b766dItTYOtX8Ey2booMJaPN7M5yOv8mh5qsWNHu+IjzTQqc8Qxy6LbkNQ7C1FFggzEq6Wp5M/3gyxKzTJC8kjn4Lz1paDTFmOLlpckrebAp6KzTB01TcGzJrzczBNZdq64jT2q2J/QNesrSSqdh+GzD5ZNuX3SD4PaTfwXr7b/HlKlr+0KHU+OhOJQkPJ7rcTzNXMuZt0fNjhdH47ksDJr+GHOodeeKPnY+fYq7NfRoq9GnKFY1OhBssyPEzeWSXzV02qFCwTdTpK2MkdHLeABdczy6IuOB1Mr470qR8YDfuW2mfU1qAv1kVQ17gBlXkMlLwj/q+hca60muzNRoUM2iCvGXsWbeInuRVUkFqZ1sObsknO1vxnZlJdTWJH0AjXEfZcN4VRaFyF9jUCSwMINZf0AQ2emj46yriH6BiyMZlXWzpa41Q2xHt+1nZ6bmsA+4pjYkh4a26XRnYvxDg4TSEXpf69SVQoKDTTN7aJ5CoXgLPXZrgLKOBCVPmbYHUn9zf2kMxR/8GmC5xcQ/sTOZZyVZsAMrKqbTsHRYbhZa5xamh2XxlnE4M7F0yjOtoSUyA9RTjThXQSxvUNTIdDTmic1cQqkT5NnxVOuoJVPZfzuvKaDIZBlnau/jeTqtE9pjAEd4rycHM2bcVDUc+WesveK3lPz2HtPFbV7xsin2SKp0GN3lQ0flHuPuPQYOFbFDUzHynwYq9ClEcHpNc1lqKFR0YSRJIQmSFPaoyo7oTHDI65X8pjWYiroQa65bjblTHPgFQxcyKktqsU7MinV7D1HIuL9f6yyHI47pS7jHeWFCniewCNQQVHgayRP7GsSabr0FHmpP5f4IyzUc0xKl4cNi1xPWbS76vNaS0qy9WkAExVdYxVmbMxXnpV/C3SOBC53w5gB/cO79rXSyduftXaDB4nXBG+ykLxfX3kxILlzE7WdrvvNQphBEIZyUrRYJfB/17XVVL8Ys1rur+OtErXw9J4hk8Ybdu259GsxUWEiw0hEHkcVyR+xP5B3CaiECeGc4d+OCdmB0pRS0lQfoAEHaCy25hHa2KoZi2zwR+onIbR6j6j4LZNhmDxwpLkAwKA2DcdNnTAacl5w8M7aHwrPknHW7CXHCm0z8QG5kOg8zqtgNGkQfEOcacf/GeJ1VH/e8UBusWZLXJwy9wwcNnrQROIZ0LVLSDd21l5ZKl0eHuEppbKw0bHS2qDLgLP8Jhy98T/830pfd3XOey5p8S/IMxac+XCAKV05YwZHsyoarbw8obrHbbJ+lST5RXxK8HWaPcLnwN8/jkKBKndbrq48oqKXv/5iIMnYyKv/waQIH+5alrKsPxi8TZvsEodg71eDzSnVJoGUbYn0gQvh6Q/juZfh2sPCQM2nffOrkcDCGyx7mS4Jp/aK6TQ1axSmYoDFLLti5JOUB8/M76dJ9DFbyQgZXU6rW2Vb3uLBgl7y8YkKeDHdAjDGRCSC6buJvbT3L1ybwBXjhBneDyJyLYW0bs9wNAVKHcIYgxOmJ7RuUq86z7UdTRCi1jYc4+uxfX0UNOdaGLNjWUJuWUGwqzzFY6jlygU19Jb6vasMUDzvg3G1yVeQxk6V5xKq0uRUIxRsk9prUCaFNXZ4T7ej3RqmaiHyiCOH2AWnYctuy++eLIQr++j8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [RCCC = _t, Unit = _t, Group = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"RCCC", type text}, {"Unit", type text}, {"Group", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Unit", "Unit-RCCC"}, {"Group", "Group-RCCC"}})
in
    #"Renamed Columns"
