//Updated 3/24/2021 by Matt Miller
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hVhbd9q6Ev4rWjzts1ZZ9RWSR2EwJDsO1KZNuy8PjhHgvR2bynZa/v2ZkWRsiaQ7DwTmG91mvrlIf/45ciz4c0YfRsHLjiQsa/KqhF+2RcPR3x8E7ts2SMLIFG+leBxEiQa5tm0hRN0xZbwi61NNklOj6yx921I6Y9tCHQ33LJgGcW8cR3MdcixbQpqYeraD4qguzdXc7oyrT0QdE348JfSCUgqCdXKni23HUobZVHVjYJ6PWP5KFt/btIADnAyFGxx8Vza8bApC9/s057Whcosq93RpiKkYaUpnKN1QQxqILR7TU5HmpYHNEUvSPWvOBvJZIHQT63LfErNVL6eGV0XBuAmjgZ+WH4OAPOXN8VgVOxR0Xzs14dkwMrbqu1ZHI03qSRYt1t8MRPArYGVDovJAkuxYVQVaEPl20UG3brYb9XkRu3i+7cbu/l0AXO0bK4rqB4nz52dB9m9xj/tyhNP9k4BLBRVm0VZ9SrHnCMqBwV4GLO/PcGtZigSMs7ohgaRREG0uCp7wapCMgUqDbxKmVIyn23Cjzbu6FyZOwmRskvY+lGE5dn2yuVtrWByJKBi47rITG45+K7ZaVq8pJgESs3SXl6yuyZYDt/LygHiszg5BLrYezOLHBYZdsuyAqbBVnJYHhu5a98DE7gBhruhrMsRvLXGqdbBWn1IcfhJGCMf2RIyCeOTDYYDbysiFLrf/Y5yN1qA5zzj7QcKiwVDOT7qOOIvnTwna+noWSEYiiKOvy/FDdSCbIi1r+btTcCadQtiywgBdqwPByOZIzxpOffGHruQrpUQy8PuuNPCZPcDhlDo8uQxfnrrDabD9K3gqR7dljpQxdnZju519031DlqxUHh/ofJEEZzyHHLqpeIOLMH0VcDBGJV0urrYfflpglgnTZzID+2VHA40nGFO8OrVFLQubhk47ftAsA8NW/Hy1Q9C6Uew68LRhO0JfYaY8q001DJ9NtHgw5fNuEXQ/+S1cbf43VJl4TiB4OBnflfuKRIeXZhhPU892Z6rUbHl5GD9W5Zhm34c61L7xxBzbgD4k3RkuqOLoQ5zoHO0VHKtTSNrTqTgb6KRDBYOvtkgVjVHjQuMe9Kzh6hqNeyVF45+1RuMev/FUpn1OGwLz5HUDPsCMK5TJU8rfm/oXHLsoeTJTo0AXiy4kWCSGeIPa87xOa0jtZMPZKeVsd7W2Jzsh1ZNcAmiIB0gbxuuqLEX+GoIigUU57PodBZGd3itnXUf0C1yUZGTWlUs9e4rYlm7UZyemVu8HPJMKyX6gY7ldTUy+G5BgOkJvc516kkhQ2Ayxj+IJNIrX0H13BmjrSFjxjBk+kPybBYtx3/zBrx6WLibBkb2QWV6ROduzsmamGrYOi/XcmNzG9LAoX3MONRNbpyI3BtoiM0A/1Yq6CmR5haZGpqOhnnDmAlqdsMgPx8ZEbZnK/umspoEik+Wc6bMP9+kqI6gygCu8NZOLGTNp6wZK/gv2XslrRn5/S9NDNy951ZY7VKpNGM0VwETVDuPuLQ1cKmb7tmbkrxY69AlEcHbOCtlqaKpowlgqRSRMM/BRnR/QmGCQ5zP53RgwEX0h9lzXHPMmuPAThi5kVJY24pyYFRt1D9GU0b+fm7yAEsfMI9zivjAhz1I4BHIIOjxDyRd+DRODt/5KpZqPKyPnTNXNAQIkOcMmX4wtUVEOgwquFinc14SxevidsvZTm2TlzVSr32JvOuctTnLpBlf+VDAqmifqU4lvfGQhxEgEhVBRjcD3wdx+19RiSGI7u0w+j/TG1nfDWPZmOL3nNcdeTIWEhEsTcRGZL7bE+UDeUFjORXxux+7NsF/tNbpOCcbK+thDkNUiWx5B7VbHkEvrB0I/EOnFHgVDifsLTEqjcAg9YixzXnHyyNgO+saKc9Z5C2jO21z8QN3Ycu+mVJOPaRi/ozgzFHevjDd5/f7Mc33AiqVFc8TI2b8z4MFYgWNENiKjXKl7zsLW1WXmFzchQxsbBQeNKZoEKMU/oHbC9+zfAX+c7pryWDXkS1rkSC793QFRuDHCCQ5kW7VcfzpA8gpvsl2epcVIfwjwtxj80WIerB+HlKdam3XhzyVioBW+/WMkutDRoHvDlwVc7Euesa68Dx8WLPWCoMk71uDrSH1KYaQKoUugQXj6fXjuZHh2sLCQO1JPNk2634/7uxqmO4JZ+aSbTQ9KzSiYXzHJzdlLRao9ptc3sp13Hy7lfQpullRvk+3ubWDOTkV1xnw66q9wGEMi0iF6ruJrZT/KxyKwBVjhCvfC2JqJZR0Hs9iVAqQGYQyhkGRHtmuRrqae49xbIkKpM75L4o/B+Vm0gENuyH5rBa1lBb2i9pqCnZorD9g2ZxIEOjcs8S4Dxt2kZ40eU9lZx6zO2muCULwA4qxpkxLaNtVLalRuf5CKicgnGhGu3396lzu2c3l90KLAt75aVN0sP4qToJVId92Q9QqvGl1VXvxkPMuhwKkiPqxic+Tp3XwLPfnuoMeM/zYsXfL3/wE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [RCCC = _t, Unit = _t, Group = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"RCCC", type text}, {"Unit", type text}, {"Group", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Unit", "Unit-RCCC"}, {"Group", "Group-RCCC"}})
in
    #"Renamed Columns"
