//Updated 3/24/2021 by Matt Miller
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hVhZd9rIEv4rfXiae050ohXsx0YgsMcyRCJxMsuDLBrQjCwRLU7497equ7V0Y2f8gKG+6q3qq6X7zz8ntgl/9uTDxH/Zk5ilTVYW8MsyaTD5+wPHPcsCSRDq4p0QG34YK5BjWSZC1DEoq0qyOdckPjeqzsqzTKljWCbqKLhrwjSIu0YULlTINi0BKWLqWjaKw7rQV3O6M64/EXlM+PEU0x6lFASb+E4VW7YpDbMt60bDXA+x7JUsv7dJDgc4awo3OPiuaKqiyQk9HJKsqjWVW1S5pytNTPlIXTpH6ZZqUp9v8ZSc8yQrNGyBWJwcWHPRkM8codtIlXsmn618OTdVmees0mE08NPqo++Tp6w5ncp8j4Lua6fGPRuE2lY9x+xopEhdwaLl5puGcH75rGhIWBxJnJ7KMkcLIt96HXTrdreVn73YwfPttlb3rwdwtW8sz8sfJMqenznZv0UD7okRdvdPAA7lVJiHO/kpxK7NKQcGexmxfDjDrWlKErCK1Q3xBY38cNsruNyrfmwAlUbfBEwpH093wVaZd33PTRwHsaGT9j4QYWk4HtnebRQsCnkUjFzX78SCo9/yrRbla4JJgEQs2WcFq2uyq4BbWXFEPJJnhyDnW/fn0eMSwy5edcCM2ypKiiNDd20GYGp1ADdX+DUe47cmP9XG38hPIQ4+cSMEhjXloyAeq/EwwC1p5FyVW/8xzkJr0KxKK/aDBHmDoZydVR1+FtebEbT19SyQjHgQh19XxkN5JNs8KWrxu1Owp51C0LJcAx2zA8HI+kjXHE/d+0NV8qRSLBj4fV9o+Nwa4XBKFZ72w1fn7nAKbP0KnonRbZEhZbSd3VhOZ9/k0JAVK6THRzpfBMFZlUEO3ZZVg4swdRVwMEYlXS2vth98WmKWCZJnMgf7pScNjaYYU1V5bvNaFDYFnXX8oGkKhi2ry9UOQetGsutYJQ3bE/oKM2Vprath+GzD5YMuX3SLoPvJb8F6+7+xytS1fc7DqXFXHEoSHl+acTzNXMuZy1Kzq4qj8VgWBk2/j3WodePyOXY+fYi7M/So5OhDFKscHRRss1OI2/M5v2jotEM5g6+2SCWNUaOn8QC65nh1hcaDkqTxz1qh8YDfuDLTPicNgXmyugEfYMblyuQpqd6b+hcc65VckalRoIp5F+IvY028Re1FVic1pHayrdg5qdj+am1XdEKyJ+kDaIz7SBtW1WVR8Pw1BnkCCzPY9TsKPDu9V866jugXOC/JyKwrl7rWDLEd3crPTkzNwQ94JhmSw0DbdLqaGH/XIM50hN7mOnUFkaCwaWIPxVNoFK+h++4M0NaRoKxSpvlA8G/uL42h+YNfAyxcTPwTeyHzrCQLdmBFzXQ1bB2Wm4U2uYXpYVm8ZhXUTGyd8kwbaPHMAP1Uy+sqkOUVmhqRjsZ63JlLaHWCPDueGh21RCr7p7OaAvJMllVMnX28T0caQZYBXOGtmRzMmHFbN1DyX7D3il9T8vtbmi66eVWVbbFHpVqH0Vw+TFTuMe7e0sClInZoa0b+aqFDn0IEp5c0F62GooomjIRSSIIkBR/V2RGNCQZ5vpDftQFT3hdiz3XNMXeKCz9h6EJGZUnDz4lZsZH3EEUZ/fu5yXIocUw/wi3uCxPyPIFDIIegw9OUPO7XINZ46y2wqD2U+yMc13BMi7eGd4tdr7CWuejjWktKM3m1gAiKL3CKF23PlNdLv4S7RwIXOm7NAX6n7v1UJlm7c3kXaLF5XVQtTtK3i2tvxikXLmL5KcU3HtIUgiiESim5SOD7aG6v63oxZrHfXcWfJ2rn6zlBJJo3nN51m9MgplxCgpWOOIgsljtifyBvKKwWPIB3hnMzbmgHja6VgrGigA4QpL3QEkeQu1UxJNvmgdAPRLh5jKp+5sjgZg8MyS9AsCgNg/HQR0wGVVVW5JGxPTSeZVWxzpsQJ1Wb8R+oG5nO3YwqcoMG0TuKc01x/8qqJqvfn3mhDlizJG9OGHqHdwY8aCtUGNINT0lX6q69tFR1UTr4VUrTxk7DRmPzLgNq+Q8ovvA9/XfEL7u75zyWDfmS5BmST324QBSunHCCI9mVbaW+PSC5ubfZPkuTfKK+JHg7zB7hcuFvHschQZU+redXH1HQS9/+MeFt7GTU/uHTBC72JUtZ1x+MXyZM+QShyDvW4PNKfU5gpAyxPhAhfL0hfPcifDuYW8iZyDefJjkcjOGyh/mSYFo/q2ZTg1YxCiZozJIL9lKS8oD5+Y106d4HK3Ehg6spVftsq3tcWLBzXl4wIU+GOyDGGM8EEF1X8be2HsVrE9gCrHCFu0Fkzvmyto1Z7koBUgc3BleI0xPbt0hXXc+2700eodQ27uLoo3955j3kmBuiYVtDb1pCs6k8x2Cr54gDts2F+L7KDZM/7IBxt8lFocdMtOYRq9P2miAUb5A4a9IkhLZN+ZJopd8bpWrC84lChOsHpMHltmX3zxdKFHjmV5PKq+lHfhK0EunuK6Lg4V2lK+vLn6xKM6iQsgu4KoOQD4lMkeO9vw0Ll/z9fw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [RCCC = _t, Unit = _t, Group = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"RCCC", type text}, {"Unit", type text}, {"Group", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Unit", "Unit-RCCC"}, {"Group", "Group-RCCC"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([#"Group-RCCC"] <> "BMT" and [#"Group-RCCC"] <> "CMS" and [#"Group-RCCC"] <> "IDT" and [#"Group-RCCC"] <> "IRT" and [#"Group-RCCC"] <> "PTP" and [#"Group-RCCC"] <> "STP1" and [#"Group-RCCC"] <> "STP2" and [#"Group-RCCC"] <> "TAP"))
in
    #"Filtered Rows"
